### ISSUE TITLE
Using f-strings is not Python 2.7 compatible

### ISSUE THREAD

**Issue by cp2004** [DavideM84/OctoPrint-IgnorePausedForUser#1]
Up to you what to do with this one, I was scrolling by and noticed some `f"string{variable}"` patterns, these don't exist in Python 2. They are awesome though, but it would probably be best if the plugin was marked accurately.

You can achieve a *similar* thing with this kind of pattern:
```python
name = "Charlie"
string = "Hello {name}".format(**locals())
```

*Personally*, for new projects I wouldn't write with Py2 support in mind, nearly 30% of users are running Python 3 and this is continuing to grow quite quickly.

**Comment by DavideM84** [comment]
I removed all the f-strings [commit](https://github.com/DavideM84/OctoPrint-IgnorePausedForUser/commit/aadb83a737f31b6a340ebc6510c0a27254ca8576)
It will be in the next release.
Thanks for report.
